project:
  type: website
  output-dir: docs 

website:
  title: "Machine Learning"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: eda.qmd
        text: EDA
      - href: laboratorio.qmd
        text: Laboratorio
      - href: clasificacion.qmd
        text: Clasificación
      - href: midterm.qmd
        text: Midterm
      - href: categorical_encoding.qmd
        text: Categorical Encoding
      - href: categorical_pipeline.qmd
        text: Categorical Pipeline
      - href: ml_text.qmd
        text: ML Text
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    fig-align: center
    df-print: paged
    embed-resources: true
